name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Nix
        uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Build
        run: nix build

      - name: Test
        run: nix develop --command go test ./...

      - name: Lint
        run: nix develop --command golangci-lint run

      - name: Check formatting
        run: nix develop --command treefmt

      - name: Verify binary works
        run: |
          nix develop --command ./result/bin/ccusage-rainbow --help
