name: Dependabot Auto-merge

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Nix
        uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Build and test
        run: |
          nix develop --command bash -c "
            echo 'Building project...'
            nix build

            echo 'Running linter...'
            golangci-lint run

            echo 'Running tests...'
            go test ./...

            echo 'Checking formatting...'
            treefmt
          "

      - name: Auto-merge minor and patch updates
        if: success()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Get PR info
          PR_TITLE=$(gh pr view ${{ github.event.pull_request.number }} --json title --jq '.title')

          # Check if it's a minor or patch update (not major)
          if echo "$PR_TITLE" | grep -E "(deps|deps-dev).*: bump.*from.*to.*" | grep -vE "from [0-9]+\.[0-9]+\.[0-9]+ to [0-9]*[02-9]+\.[0-9]+\.[0-9]+"; then
            echo "Auto-merging minor/patch dependency update"
            gh pr merge ${{ github.event.pull_request.number }} --auto --squash
          else
            echo "Major version update detected, skipping auto-merge"
          fi
